language: python
python:
    - "2.7"
virtualenv:
    system_site_packages: true
before_install:
    - sudo apt-get install python-numpy python-scipy
install:
    - pip install coveralls
script:
    coverage run --source=boldsim tests/test_sim.py
after_success:
    coveralls
